{{ if .Values.gremlin.podSecurity.podSecurityPolicy.create }}
---
apiVersion: {{ include "pspApiVersion" . }}
kind: PodSecurityPolicy
metadata:
  name: chao
  annotations:
    # add 'unconfined' to this list if you wish to run Process Killer attacks against host (e.g. 'docker/default,runtime/default,unconfined')
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'docker/default,runtime/default'
    # apparmor.security.beta.kubernetes.io/allowedProfileNames: 'runtime/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  'runtime/default'
    # apparmor.security.beta.kubernetes.io/defaultProfileName:  'runtime/default'
spec:
  privileged: false
  # Required to prevent escalations to root.
  allowPrivilegeEscalation: false
  # This is redundant with non-root + disallow privilege escalation,
  # but we can provide it for defense in depth.
  requiredDropCapabilities:
    - ALL
  # Allow core volume types.
  volumes:
    # hostPath volumes are required by Gremlin as attack logs and attack state are stored on the host at
    # /var/lib/gremlin
    # /var/log/gremlin
    - 'secret'
  # set hostNetwork to true if you wan to run network attacks against the host
  hostNetwork: false
  hostIPC: false
  # set hostPID to true if you wan to run Process Killer attacks against the host
  hostPID: false
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    # This policy assumes the nodes are using AppArmor rather than SELinux.
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
  readOnlyRootFilesystem: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: psp:chao
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
rules:
  - apiGroups: ['policy']
    resources: ['podsecuritypolicies']
    verbs:     ['use']
    resourceNames:
      - chao
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default:chao
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp:chao
subjects:
  - kind: ServiceAccount
    name: chao
    namespace: {{ .Release.Namespace }}
{{ end }}