{{- if and .Values.chao.tls.identity.enabled .Values.chao.tls.identity.createSecret.name (and .Values.chao.tls.identity.createSecret.cert .Values.chao.tls.identity.createSecret.key) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.chao.tls.identity.createSecret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "gremlin.name" . }}
    helm.sh/chart: {{ include "gremlin.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    version: v1
type: kubernetes.io/Opaque
data:
  cert: {{ .Values.chao.tls.identity.createSecret.cert | toString | b64enc }}
  key: {{ .Values.chao.tls.identity.createSecret.key | toString | b64enc }}
{{- end }}
