{{- if .Values.ssl.certFile }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ssl-cert-file
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gremlin.labels" . | nindent 4 }}
type: kubernetes.io/Opaque
data:
  certfile.pem: {{ default .Values.ssl.certFile | toString | b64enc }}
{{- end }}
