{{- if .Values.gremlin.secret.managed }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gremlin.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gremlin.labels" . | nindent 4 }}
type: kubernetes.io/Opaque
stringData:
  GREMLIN_CLUSTER_ID: {{ default .Values.gremlin.clusterID .Values.gremlin.secret.clusterID | required "required: .Values.gremlin.secret.clusterID" | toString }}
  GREMLIN_TEAM_ID: {{ default .Values.gremlin.teamID .Values.gremlin.secret.teamID | required "required: .Values.gremlin.secret.teamID" | toString }}
{{- if (eq (include "gremlin.secretType" .) "secret") }}
  GREMLIN_TEAM_SECRET: {{ .Values.gremlin.secret.teamSecret | required "required: .Values.gremlin.secret.teamSecret" |  toString }}
{{- else if (eq (include "gremlin.secretType" .) "certificate") }}
{{- if (hasPrefix "-----BEGIN" .Values.gremlin.secret.certificate) }}
  GREMLIN_TEAM_CERTIFICATE_OR_FILE: file:///var/lib/gremlin/cert/gremlin.cert
{{- else }}
  GREMLIN_TEAM_CERTIFICATE_OR_FILE: {{ .Values.gremlin.secret.certificate }}
{{- end }}
{{- if (hasPrefix "-----BEGIN" .Values.gremlin.secret.key) }}
  GREMLIN_TEAM_PRIVATE_KEY_OR_FILE: file:///var/lib/gremlin/cert/gremlin.key
{{- else }}
  GREMLIN_TEAM_PRIVATE_KEY_OR_FILE: {{ .Values.gremlin.secret.key }}
{{- end }}
data:
{{- if (hasPrefix "-----BEGIN" .Values.gremlin.secret.certificate) }}
  gremlin.cert: {{ .Values.gremlin.secret.certificate | required "required: .Values.gremlin.secret.certificate" | toString | b64enc }}
{{- end }}
{{- if (hasPrefix "-----BEGIN" .Values.gremlin.secret.key) }}
  gremlin.key: {{ .Values.gremlin.secret.key | required "required: .Values.gremlin.secret.key" | toString | b64enc }}
{{- end }}
{{- end }}
{{- end }}
