{{- if (default .Values.gremlin.client.certCreateSecret .Values.gremlin.secret.managed) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gremlin.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "gremlin.name" . }}
    helm.sh/chart: {{ include "gremlin.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    version: v1
type: kubernetes.io/Opaque
stringData:
  GREMLIN_TEAM_ID: {{ default .Values.gremlin.teamID .Values.gremlin.secret.teamID | required "required: .Values.gremlin.secret.teamID" | toString }}
{{- if (eq (include "gremlin.secretType" .) "secret") }}
  GREMLIN_TEAM_SECRET: {{ .Values.gremlin.secret.teamSecret | required "required: .Values.gremlin.secret.teamSecret" |  toString }}
{{- else if (eq (include "gremlin.secretType" .) "certificate") }}
  GREMLIN_TEAM_CERTIFICATE_OR_FILE: file:///var/lib/gremlin/cert/gremlin.cert
  GREMLIN_TEAM_PRIVATE_KEY_OR_FILE: file:///var/lib/gremlin/cert/gremlin.key
data:
  gremlin.cert: {{ default .Values.gremlin.client.certContent .Values.gremlin.secret.certificate | required "required: .Values.gremlin.secret.certificate" | toString | b64enc }}
  gremlin.key: {{ default .Values.gremlin.client.keyContent .Values.gremlin.secret.key | required "required: .Values.gremlin.secret.key" | toString | b64enc }}
{{- end }}
{{- end }}
