{{- if .Values.ssl.certFile }}
---
apiVersion: v1
kind: Secret
metadata:
  name: integrations-ssl-cert-file
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "gremlin.name" . }}
    helm.sh/chart: {{ include "gremlin.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    version: v1
type: kubernetes.io/Opaque
data:
  certfile.pem: {{ default .Values.ssl.certFile | toString | b64enc }}
{{- end }}
