#!/usr/bin/env bash
# Shared regenerate-and-diff reporter, used only by CI (pre-commit has its
# own equivalent built in: a hook that modifies a file blocks the commit).
#
# usage: check-drift.sh <what> <fix-command> [--tool "<name> <version>"] <path>...
#   what   - human name of the artifact, e.g. "README.md"
#   fix    - the command that regenerates it, e.g. "make docs"
#   --tool - optional; the generator name+version that produced today's
#            output, printed above the diff in the failure BODY, never in
#            the ::error title and never asserted on (design.md 4.4) - a
#            version mismatch is a rare cause of drift, not the likely one,
#            and asserting on it would re-impose through CI the tolerance
#            B5 deliberately grants a contributor's unpinned local tool.
#
# The ::error file=...:: annotation is what makes a failure legible without
# opening the job log: GitHub attaches it to the stale file in the PR's
# Files-changed tab, naming which file is stale and what command fixes it.
set -euo pipefail

usage="usage: check-drift.sh <what> <fix-command> [--tool \"name version\"] <path>..."

what="${1:?$usage}"
fix="${2:?$usage}"
shift 2

tool=""
if [ "${1:-}" = "--tool" ]; then
    tool="${2:?--tool requires a value}"
    shift 2
fi

paths=("$@")
[ "${#paths[@]}" -gt 0 ] || { echo "$usage" >&2; exit 2; }

if git diff --quiet -- "${paths[@]}"; then
    exit 0
fi

while IFS= read -r f; do
    echo "::error file=${f}::${what} is out of date. Run '${fix}' and commit the result."
done < <(git diff --name-only -- "${paths[@]}")

[ -n "$tool" ] && echo "generated by ${tool}"
git --no-pager diff -- "${paths[@]}"
exit 1
